### ISSUE TITLE
Overlay中添加多线段数量级达到上万次时会出现渲染不稳定现象

### ISSUE THREAD

**Issue by blchock** [LiXizhi/NPLRuntime#139]
-- 绘制地表网格
function Manipulator:createSurfaceMesh(po)
	local names = {};
	local width,litWidth = 1024,2
	local halfw = width / 2
	local overlay = Overlay:new():init();
	overlay:SetPosition(po.x,po.y,po.z)
	overlay.paintEvent = function(self, painter)
		painter:SetPen({width=0.02});
		local isDrawingPickable = self:IsPickingPass();
		local main_name, lit_name;
		if(isDrawingPickable) then
			main_name = self:GetNextPickingName();
			lit_name = self:GetNextPickingName();
		else
			main_name = names.main
			lit_name = names.lit
		end
		self:SetColorAndName(painter, "#000000", main_name);
		ShapesDrawer.DrawLine(painter, - halfw,0,0, halfw,0,0);
		ShapesDrawer.DrawLine(painter, 0,0,- halfw, 0,0,halfw);
		self:SetColorAndName(painter, "#FFFFFF", lit_name);
		for i = - halfw, halfw, litWidth do
			if i ~= 0 then
				ShapesDrawer.DrawLine(painter, - halfw,0,i, halfw,0,i);
			end
		end
		for j = - halfw, halfw, litWidth do
			if j ~= 0 then
				ShapesDrawer.DrawLine(painter, j,0,- halfw, j,0,halfw);
			end
		end
		if(isDrawingPickable) then
			names.main = main_name;
			names.lit = lit_name;
		end
	end
	self.meshOverlay = overlay
end

**Comment by kkvskkkk** [comment]
painter:EnableAutoLineWidth(false) 关掉自动缩放 
开启自动缩放时 c++会根据顶点坐标和摄像头位置调整宽度。 这里的lua代码 线条数量不一样时 顶点坐标是不一样的
