### ISSUE TITLE
需求TableDatabase的close接口

### ISSUE THREAD

**Issue by nustxujun** [LiXizhi/NPLRuntime#158]
主要是为了解决TableDatabase open之后，一直占用db文件的问题

**Comment by LiXizhi** [comment]
I think there is an undocumented  `collection:Close()` method, did you try that? If it is not working, I will fix it.

**Comment by nustxujun** [comment]
有close(),  不过close之后就无法重新打开了

**Comment by LiXizhi** [comment]
fixed in master and next release
