### ISSUE TITLE
lt做热更新时，mian.zip 和model.zip运行时，命令执行后部分页面显示不了。

### ISSUE THREAD

**Issue by adkevinchang** [LiXizhi/NPLRuntime#160]
做热更新还遇到个问题，main.zip运行的话。我们的model里的Commands["bluetoothfilemonitor"] 命令执行时，有个html页面显示不出来？日志里也没报错。但是不打包成zip就正常。
这个命令bluetoothfilemonitor，是电影方块里执行的。

**Comment by LiXizhi** [comment]
can you decribe in details as for the environment and paths and code. provide as much info as possible here.

**Comment by hetter** [comment]
bluetoothfilemonitor是我在mod加的命令，会执行一个Task，并且会show一个mcml出来，简单来讲就是电影方块结束后触发命令方块，命令里面添加一个ui失败了。

更详细的原因我想还是我这边先用一个简单的世界来重现这个问题，然后再多打几行日志来排查吧。。

**Comment by hetter** [comment]
@adkevinchang  已经定位问题，是清除fbx骨骼时候获取电影方块坐标会报错，我打算做一个pc环境下跑电影的功能，到时候一起上传，如果急着改我可以先告诉你代码位置。

**Comment by adkevinchang** [comment]
不是很急。先测试稳定。

**Comment by adkevinchang** [comment]
问题已解决。
