### ISSUE TITLE
miniscene层级过高，ui控件被挡住

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#236]
具体操作：在miniscene中显示一个模型，再在同位置显示一个对话框，该UIObject设置zorder为任何值都会被模型覆盖。
原因定位：可能是viewport问题，miniscene与ui的视口不同，不知道该如何解决
相关代码：EntranceView:createRoleCanvas()。
![qq 20180205090856](https://user-images.githubusercontent.com/20142948/35784594-401d7922-0a54-11e8-8856-573f8dfca594.jpg)

**Comment by LiXizhi** [comment]
you can use miniscene graph with owner draw. it is just a standard texture. 

`NPL.load("(gl)script/ide/Canvas3D.lua");`  is an old example used in haqi

**Comment by Elshadow** [comment]
Which control would you use for implementing it in the latest version code for instead of using Canvas3D, Cause I still didn't understood what 'use miniscene graph with owner draw' was. Could you please describe it with more details or offer us with a sample code might be better.Thx anyway.

**Comment by LiXizhi** [comment]
you can search for Canvas3D in the code. 

`script/apps/Aries/Creator/Game/Tasks/SelectModelTask.html`
might be a sample

```
<pe:canvas3d miniscenegraphname="LeftTopCanvas128" RenderTargetSize="128" autoRotateSpeed="0.12" style="width:128;height:128;" value='<%=GetParams()%>' />
```

![image](https://user-images.githubusercontent.com/94537/36085023-828c813c-0ffd-11e8-91dd-ecfd1e1e3a6f.png)

**Comment by LiXizhi** [comment]
https://github.com/LiXizhi/NPLRuntime/wiki/MiniScenegraph

see also wiki

**Comment by Elshadow** [comment]
so in your opinion, we should use mcml2 to implement it?
