### ISSUE TITLE
使用DynamicVertexBuffer绘制的标线在旋转视角时会闪烁

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#242]
渲染代码如图所示：
![qq 20180207190813](https://user-images.githubusercontent.com/20142948/35913356-4da3d32e-0c3a-11e8-9d33-ff7d299b03df.png)
![qq 20180207190818](https://user-images.githubusercontent.com/20142948/35913361-5056074a-0c3a-11e8-9615-899564059789.png)
其中DVB_GIS_DELINEATER是新添加的一个顶点缓冲类型。
现象如视频所示：
[智慧地球 -- 0.0.1 2018_2_6 10_32_51.zip](https://github.com/LiXizhi/NPLRuntime/files/1702808/--.0.0.1.2018_2_6.10_32_51.zip)

注：2018.2.9之前必须解决。

**Comment by LiXizhi** [comment]
why you need to create a new buffer type when there is already "DVB_XYZ_TEX1_NORM" ? 
Just use that buffer to draw, unless you are adding a new vertex format

**Comment by kevinypcao** [comment]
使用DVB_XYZ_TEX1_NORM也会有同样的问题！

**Comment by kevinypcao** [comment]
使用DVB_XYZ_TEX1_NORM的时候连模型都会受影响跟着一起闪烁！
