### ISSUE TITLE
怎么实现实现创意空间中摄像机拉近时隐藏角色

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#249]
详细见视频：

[创意空间 ParaCraft -- ver 0.7.351 2018_2_9 14_37_49.zip](https://github.com/LiXizhi/NPLRuntime/files/1709984/ParaCraft.--.ver.0.7.351.2018_2_9.14_37_49.zip)

**Comment by LiXizhi** [comment]
```
obj:SetField("opacity", opacity or 1);
```

**Comment by kevinypcao** [comment]
@LiXizhi 创意空间实现摄像机拉近时角色淡入淡出功能的代码在哪一块，可以直接拿过来参考一下吗？
