### ISSUE TITLE
release版本，overlay物体在转动视角时可能会出现抖动

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#252]
详见视频：
[智慧地球 -- 0.0.1 2018_2_8 17_03_02.zip](https://github.com/LiXizhi/NPLRuntime/files/1710011/--.0.0.1.2018_2_8.17_03_02.zip)

**Comment by LiXizhi** [comment]
you did not update the relative-to-camera position on each render frame. 

```lua
function Overlay:Tick()
	if(self:IsUseCameraPos()) then
		self:UpdateToCameraPosition();
	end
end
```

**Comment by e-setup** [comment]
@LiXizhi 这个情况，是在paraengine编译成release版本的时候会出现，如果使用debug版本就不会抖动。lua代码是同样的。你提及的UseCameraPos我也试了，没有起作用。还有什么原因会导致这个吗？这个问题我们现在还是没有解决哦。
![default](https://user-images.githubusercontent.com/16555532/36069244-d0e18e32-0f20-11e8-8c6d-e4cdbc9e757d.png)
