### ISSUE TITLE
怎么在ParaEngine中给FBX模型做LOD

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#254]

**Comment by LiXizhi** [comment]
see FBX wiki, you need multiple fbx files or parax file.  This is done manually. 

use /export command to convert to ParaX file. instead of using fbx directly.

**Comment by kevinypcao** [comment]
那如果要用程序去给FBX模型做LOD有什么办法吗？

**Comment by LiXizhi** [comment]
暂时没有， 如果一定要做，只能自己写C++代码。 参考BMAX LOD的做法。
