### ISSUE TITLE
怎么让角色的阴影能映射到摆到场景的模型上面

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#255]

**Comment by LiXizhi** [comment]
it is on by default. if not, you may need to set receive shadow attribute on the shadow receiver

**Comment by kevinypcao** [comment]
@LiXizhi 我设置了ShadowReceiver属性，但是阴影并没有投影到模型上面，是不是我哪个地方使用不当？我尝试着在魔法哈奇中开启阴影效果，发现角色阴影同样也没投影到模型上。
![qq 20180211145553](https://user-images.githubusercontent.com/20142948/36070715-afe28cb6-0f3b-11e8-875b-e472c93065ee.png)

**Comment by LiXizhi** [comment]
默认没有设置shadow receiver.  shadow receiver需要渲染2次。

**Comment by kevinypcao** [comment]
我在智慧地球中也给所有的模型设置了ShadowReceiver属性，但是阴影并没有投影到模型上面。

**Comment by LiXizhi** [comment]
这个功能很久没有试过了。要让开发看下。 @kkvskkkk
