### ISSUE TITLE
怎么在ParaEngine中开启抗锯齿效果

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#256]

**Comment by LiXizhi** [comment]
there is an option in config.txt, but only possible during restart. 
The better way is to use deferred shading to do AA manually in shader as in paracraft /shader 2

**Comment by kevinypcao** [comment]
@LiXizhi 开启抗锯齿不生效，提示如下图所示：
![qq 20180211142152](https://user-images.githubusercontent.com/20142948/36070513-12054f3c-0f37-11e8-952e-a05368fa8fd7.png)

**Comment by LiXizhi** [comment]
due to deferred shading. hardware AA is always disabled. Use software shader based AA instead. see Paracraft's shader code.  I suggest you disable AA, and do software based AA like in paracraft.

**Comment by kevinypcao** [comment]
shader文件名是啥？
