### ISSUE TITLE
NPL.load() 不能加载.npl

### ISSUE THREAD

**Issue by caoyongfeng0214** [LiXizhi/NPLRuntime#30]
例如：
local a = NPL.load('a');
有文件 npl_mod/a/a.npl
无法加载此文件。
如果将 a.npl 改为 a.lua，则正常。

**Comment by LiXizhi** [comment]
fixed

**Comment by caoyongfeng0214** [comment]
问题未解决。
如果文件扩展名是 .npl，通过 NPL.load('a') 能得到一个 table，但并不是想要的那个 table。
如：
有文件 npl_mod/a/a.npl
var A = NPL.export();
A.name = 'Hello  A';

在另一个文件 b.npl 中有以下代码：
var a = NPL.load('a');
print(a.name);  ===> 这里输出 nil
for k, v in pairs(a) do
    print(k);
end
这里输出的是：
SetSourceName
AddDNSRecord
DoesFileExist
DeleteRuntimeState
.........

**Comment by LiXizhi** [comment]
wait for next release. or use CI release
