### ISSUE TITLE
键盘按下时没有释放事件

### ISSUE THREAD

**Issue by kevinypcao** [LiXizhi/NPLRuntime#356]
不能注册键盘释放事件
![default](https://user-images.githubusercontent.com/20142948/47889253-ff4b3100-de83-11e8-8ba4-23f8b3987f92.png)

**Comment by LiXizhi** [comment]
added key release event handler. git pull from package/main 

```lua
function EditContext:keyReleaseEvent(event)
	EditContext._super.keyReleaseEvent(self, event);
	if(event:isAccepted()) then
		return
	end
end
```
