### ISSUE TITLE
全屏状态下，ctrl+tab切换至其他程序，再切换回来，设备丢失问题

### ISSUE THREAD

**Issue by higter** [LiXizhi/NPLRuntime#373]
全屏状态，再次激活程序窗口时：
函数：CParaEngineApp::MsgProcApp( HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam )没有接收到WM_ACTIVATEAPP消息。

原因是：
CD3DApplication::Render3DEnvironment(bool bForceRender)函数，检查到设备丢失时，不再调用
HRESULT CParaEngineApp::Render3DEnvironment(bool bForceRender /*= false*/)

但是：windows系统的WM_ACTIVATEAPP消息是在该函数里，调用的FrameMove函数里转发的。

最终现象：引擎重置设备，需要WM_ACTIVATEAPP消息，而接受WM_ACTIVATEAPP消息，又需要设备状态正常。

**Comment by LiXizhi** [comment]
since we never use fullscreen mode now, I made a quick fix. 

https://github.com/LiXizhi/NPLRuntime/commit/de38acb3d92a67db2ee23e4ca3c303c10f2a2a9a

> Please config the monitor resolution first. Since it will use window mode to simulate screen mode

**Comment by kevinypcao** [comment]
@LiXizhi 通过下面的代码的确可以实现全屏：
ParaEngine.GetAttributeObject():GetField("IsFullScreenMode",true)
ParaEngine.GetAttributeObject():CallField("UpdateScreenMode")

但是切换全屏之后想要换回窗口模式把IsFullScreenMode设置为false不能退出全屏

**Comment by higter** [comment]
问题没有解决。 @LiXizhi

**Comment by LiXizhi** [comment]
fixed on Dev branch

**Comment by higter** [comment]
config.txt中StartFullscreen设置为true，
ctrl+tab切换窗口，会导致渲染暂停。屏幕呈全白色。
