### ISSUE TITLE
profiler性能分析工具

### ISSUE THREAD

**Issue by higter** [LiXizhi/NPLRuntime#379]
要求开发profiler性能开发工具
1，分类统计内存，cpu，gpu占用时间，内存消耗量

2，按渲染对象查询被调用次数，内存，cpu，gpu占用时间，内存消耗量

**Comment by LiXizhi** [comment]
See in paracraft, Ctrl + F3. 
![image](https://user-images.githubusercontent.com/94537/51156802-25e00c00-18b8-11e9-93c4-dbe91b57a7d1.png)

使用Nvidia。 Intel或 MS的显卡调试工具可以看到所有信息。 

使用visual studio可以看到CPU，内存方面的信息
