### ISSUE TITLE
使用 npl 或 npls 命令执行一个文件的时候，不要弹出新的窗口。

### ISSUE THREAD

**Issue by caoyongfeng0214** [LiXizhi/NPLRuntime#38]
使用 npl 或 npls 命令执行一个文件的时候，不要弹出新的窗口。

![a](https://cloud.githubusercontent.com/assets/14923844/25611539/05750428-2f5a-11e7-88ab-e8ae2e06eb13.png)

**Comment by kkvskkkk** [comment]
npl命令可能会显示3d图像， 所以必须有一个窗口
npls现在的改动是如果是从控制台启动则附加到当前控制台， 如果不是从控制台启动则创建一个控制台

**Comment by LiXizhi** [comment]
Fixed in next release (已经修复，等下个版本发布. )  Thanks
