### ISSUE TITLE
buffer picking 返回结果

### ISSUE THREAD

**Issue by e-setup** [LiXizhi/NPLRuntime#48]
应用buffer picking 返回的结果是一个整型数据集合。而常规拾取本身期望能获取鼠标当前选中的场景中的对象。

调用代码：
NPL.load("(gl)script/ide/System/Scene/BufferPicking.lua");
local BufferPicking = commonlib.gettable("System.Scene.BufferPicking");
local result = BufferPicking:Pick(nil, nil, 2, 2);

**Comment by LiXizhi** [comment]
it is by design. it is a region to allow some error. if you do not want it, use 1,1 as input
