### ISSUE TITLE
HLSL cross platform compiler-> mid lang --> other lang

### ISSUE THREAD

**Issue by LiXizhi** [LiXizhi/NPLRuntime#60]
we want to share our shader code with both directX and openGL. 
Right now, we have to write separate almost identical shader files for directX and openGL.

**Comment by qq573011406** [comment]
## 一 目前的情况
目前的Shader需要写2份(GLSL,HLSL),其中GLSL还要针对opengl 和 opengles分别写代码.
## 二 需求
希望只写一份Shader代码

## 三 方案

### 概览
目前有以下几种解决方案:
1.  在源代码级别将HLSL翻译为GLSL, 或者GLSL到HLSL (hlsl2glslfork) **Unity使用的解决方案,缺点是只支持DX9**
2.  将HLSL的byte code翻译成GLSL 。**在Byte code进行翻译，会更简单，兼容性更好,仅支持DX11**
3.  二进制中间语言SPIR-V。 HLSL->SPIR-V->GLSL **未来趋势，缺点是工具链不完善**
###  方案一 源代码级别翻译
#### 可用的工具有:
- **hlsl2glslfork** - by Unity: DX9的HLSL转换到GLSL 1.xx 和GLSL ES(支持ES3). unity的shaderlab就是在hlsl2glslfork的基础上搞了个包装, 确实可用, 但是不支持DX10/11.
- **hlslparser**: 来源未知. DX9的HLSL转换到GLSL3.1
 **缺点是，只支持DX9**
### 方案二 将HLSL的字节码翻译成GLSL
![image](https://user-images.githubusercontent.com/5946397/30521885-d73efcc8-9bf9-11e7-8726-a6d15354128d.png)
#### 可用的工具有
- **DXBC2GLSL** KlayGE引擎团队成员开发的工具，可以将HLSL的字节码转换为HLSL。支持dx11
- **HLSLcc**  跟DXBC2GLSL功能类似。支持dx11
**缺点是，在非Windows平台需要通过wine来执行HLSL编译。**
### 方案三  二进制中间语言SPIR-V
SPIR-V和DXBC类似，都是一个shader的二进制中间语言。但比起DXBC，SPIR-V的标准是开放的，有相应的生态系统，解析起来容易得多，这个是未来的跨平台Shader的方向，但是工具链还没有打通，缺少HLSL->SPIR-V编译器。
![image](https://user-images.githubusercontent.com/5946397/30521888-de83d30a-9bf9-11e7-869d-72f735939237.png)

####  HLSL->SPIR-V编译器
这件事情，已经有Khronos的人在做了[Complete HLSL -> SPIR-V translator · Issue #362 · KhronosGroup/glslang](http://link.zhihu.com/?target=https%3A//github.com/KhronosGroup/glslang/issues/362)，但终归不是最好的方法，进度和发展速度都缺乏管理。
#### SPIR-V->GLSL/ESSL

这有[KhronosGroup/SPIRV-Cross](http://link.zhihu.com/?target=https%3A//github.com/KhronosGroup/SPIRV-Cross)，是一个已经解决的问题。


@LiXizhi  你看一下，选择一个方案。我后续来做。

**Comment by qq573011406** [comment]
@(未分类)
# NPL引擎 跨平台Shader编译项目 阶段计划

### 周期 38天 2017/09/22~2017/10/30
### 共3个阶段

### 第一阶段 完成glEffects 库 和 dxEffects2glEffects 工具开发
#### 时间
周期:9天
启动时间:2017/09/22
结束时间:2017/10/01
#### 工作内容
**一 开发一个glEffects库**

> 这个库用来解析 glEffects文件. glEffects文件类似DirectX Effects 文件(用来描述technique pass
> unifrom RenderState VertexShader PixelShader等信息).

**二 开发dxEffects2glEffects工具**

> 这个工具用来把DirectX Effects 翻译成 glEffects.

#### 交付内容
- glEffects 库
- dxEffects2glEffects 工具 (windows/mac command tool)
### 第二阶段 整合glEffects库到NPL引擎
周期:14天
启动时间:2017/10/09
结束时间:2017/10/23
#### 工作内容
**一 把glEffects库整合到NPL引擎中**
> 配合CEffectFileOpenGL使用

**二 确定shader开发工作流程**
>给出一个文档,说明如何维护现有Shader和开发新Shader.以及如何使用 dxEffects2glEffects 工具.

**三 修改现有Shader加载逻辑**
>根据不同的平台加载相应平台的Shader.

#### 交付内容
- NPL引擎整合过glEffects和dxEffects2glEffects 的代码.
- NPL引擎修改过Shader加载逻辑的代码.
- Shader维护/开发流程的说明文档
### 第三阶段 测试&调优&Debug
周期:7天
启动时间:2017/09/24
结束时间:2017/10/30
#### 工作内容
**一 确保Windows平台正常运行原有的shader**
>保证之前的功能不会受到影响

**二 确保OSX平台正常运行 翻译过的glsl shader**
>OSX 平台测试&Debug. 对翻译过来的Shader进行手动兼容性调整

**三 确保Android平台正常运行 翻译过的 gles shader**
>Android平台测试&Debug. 对翻译过来的Shader进行手动兼容性调整

**四 确保iOS平台正常运行 翻译过的 gles shader**
>iOS平台测试&Debug . 对翻译过来的Shader进行手动兼容性调整
#### 交付内容
- 经过兼容性调整过的shader代码.
- 解决已知Bug.

**Comment by qq573011406** [comment]
[CEffectFileOpenGL修改方案 for ParacraftMobileIos.pdf](https://github.com/LiXizhi/NPLRuntime/files/1397211/CEffectFileOpenGL.for.ParacraftMobileIos.pdf)

**Comment by LiXizhi** [comment]
OK 先按照这个思路做
