### ISSUE TITLE
编辑框控件editbox中文本字体居中对齐了，但光标还是处于最左边

### ISSUE THREAD

**Issue by blchock** [LiXizhi/NPLRuntime#85]
我调用ide\gui_helper.lua 中的_guihelper.SetUIFontFormat(uiobject, format) 设置了editbox的文本位置format=5，文本居中对齐了但光标却还是左对齐

**Comment by kkvskkkk** [comment]
c++代码已上传  
lua代码里设置text的对齐方式后， selected_text也要设置成相同的对齐方式
